var GAME_LEVELS = [
  ["                                                                              ",
  "                                                                               ",
  "                                   o                                           ",
  "                                                                               ",
  "                                o  o  o        yyyy               o            ",
  "                                        =               o o                    ",
  "                              xxxxxxxxxxx                     o o o             ",
  "                              xxxxx                   yyyyy                    ",
  "                           xxxxx      v        o o                 =           ",
  "          o o              xxxxx                            xxxxxxxx           ",
  "                       xxxxxx                 xxxx                             ",
  "                       xxxxxx                                  o      pp     w ",
  "       xxxxxxx   yy                                                            ",
  "       xxxxxxx                   o o     yyyyy                    yyy        xx",
  "   xxxxxx!!!!!!!!!!!!x     j                                               xxxx",
  "@  xxxxxx!!!!!!!!!!!!x          xxxxx                 xxxxxx            xxxxxxx",
  "xxxxxxx!!!!!!!!!!!!!!xyyyyxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!"],

  ["                                                                              ",
   "                                                                              ",
   "                 o                                  o                         ",
   "                                                                              ",
   "                 o                                   !                        ",
   "                                                                      v       ",
   "  o    xx!!!xxy!yyy!xx!!!xx    o     o           xxyxxx                       ",
   "                     v                                                        ",
   "  yy  o                     !     !     !   yyy       o                       ",
   "                                                 yy                           ",
   "      yy                  xxxxyyxxxxxyyxxxx          xxx     o o              ",
   "x     v      xxxx                                                             ",
   "xx          xxxx                                                              ",
   "xx                    j                        ypy          xx!!xx     w     x",
   "xx@               xxxxxxxx!!!xxxxxx                      xxxxx!!xxxxx       xx",
   "xxxxx!!!!xxxx!!!xxxxxxxxx!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!xxxxxxx!!xxxxxxx!!xxxxx"],

   ["                                                                              ",
   "                                                                               ",
   "                                                 o                             ",
   "                                                                               ",
   "                   v                            yyyy                o          ",
   "                                                        o o                    ",
   "                                                                               ",
   "                                o o o            yy yy    pp                   ",
   "                                          o o                                  ",
   "            o o o      xxxxxxx               yyy              xxxx             ",
   "                                      yyy      v       xxxx                    ",
   "       =                   o                                o                  ",
   "       xxxxxxxxxx  xxxx!!xxxxxx!!xxx    o                               xx     ",
   "       xxxxxxx                                                      x   xx o o ",
   "   xxxxxx!!!!!!!!!!!!x                  xx     v                x       xx w o ",
   "@  xxxxxx!!!!!!!!!!!!x      j   xxxxx                 xxxxxx            xx o o ",
   "xxxxxxx!!!!!!!!!!!!!!xyyyyxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!"],

   ["                                                                                                    ",
    "  ooooo       ooooo  oooooooooo  oooo     oooo      oooooo     oooo   oooooo  oooo  ooooooo    ooo  ",
    "   oooooo    ooooo   oooooooooo  oooo     oooo      oooooo     oooo   ooooo   oooo  ooo ooo    ooo  ",
    "    oooooo   ooooo   ooo    ooo  oooo     oooo       oooooo    oooo   ooooo   oooo  ooo  ooo   ooo  ",
    "        ooooo        oo      oo  oooo     oooo       oooooo    oooo   oooo    oooo  ooo   ooo  ooo  ",
    "        ooooo        oo      oo  oooo     oooo        oooooo   oooo  oooo     oooo  ooo   ooo  ooo  ",
    "        ooooo        ooo    ooo  oooo     oooo        oooooo   oooo  oooo     oooo  ooo   oooo ooo  ",
    "        ooooo        oooooooooo  ooooooooooooo         oooooooooooooooooo     oooo  ooo   oooooooo  ",
    " @      ooooo        oooooooooo  ooooooooooooo         ooooooooooooooooo      oooo  ooo   oooooooo  "]

  ];

if (typeof module != "undefined" && module.exports) {
  module.exports = GAME_LEVELS; }
